version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: db-gr2-container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # QUAN TRỌNG: Để giữ lại dữ liệu khi container dừng
    networks:
      - app-network
  
  backend:
    build: 
      context: ./BE/api
      dockerfile: Dockerfile
    container_name: be-gr2-container
    restart: always
    ports:
      - "${PORT}:5000"
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
        # - GEMINI_API_KEY=${GEMINI_API_KEY}
        # - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
        # - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
        # - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    depends_on:
      - db
    env_file:
      - .env

# 3. Khai báo Volume (Ổ cứng ảo lưu dữ liệu DB)
volumes:
  pgdata:

# 4. Khai báo Network (Để 2 thằng nhìn thấy nhau)
networks:
  app-network:
    driver: bridge